dependencies:
  build:
    - python:3.6.3
    - anaconda3:4.3.30

build_targets:
  - name: python36
    environment: 
      - OPTIONAL_DEPS=true 
      - TRAVIS_PYTHON_VERSION="3.6"
    commands:
      - conda install pip numpy Cython
      #- source activate test-environment
      - conda install scipy cvxopt
      - pip install --upgrade --ignore-installed -r requirements_testing.txt     
      - pip install .
      - pip install -r requirements_optional.txt
      - python -m pytest dit
      #  sudo $TRAVIS_PYTHON_VERSION -m pytest -m "not cython" dit;
      - pytest --numprocesses=auto dit;
      # pytest -m "not cython" --numprocesses=auto dit;
      #- cp .coverage $TRAVIS_BUILD_DIR
      #- cd $TRAVIS_BUILD_DIR
      #- python fixcoverage.py ".*/dit/" "$TRAVIS_BUILD_DIR/dit/"
      #- codecov
      
ci:
  builds:
    - name: python36
      build_target: python36
   
