dependencies:
  build:
    - anaconda3:latest

build_targets:
  - name: python35
    commands:
      - conda install pip numpy Cython python=3.5
      - conda install scipy cvxopt
      - pip install --upgrade --ignore-installed -r requirements_testing.txt     
      - pip install .
      - pip install -r requirements_optional.txt
      - pytest --numprocesses=auto dit

  - name: python36
    commands:
      - conda install pip numpy Cython python=3.6
      - conda install scipy cvxopt
      - pip install --upgrade --ignore-installed -r requirements_testing.txt     
      - pip install .
      - pip install -r requirements_optional.txt
      - pytest --numprocesses=auto dit
      
  - name: python37
    commands:
      - conda install pip numpy Cython python=3.7
      - conda install scipy cvxopt
      - pip install --upgrade --ignore-installed -r requirements_testing.txt     
      - pip install .
      - pip install -r requirements_optional.txt
      - pytest --numprocesses=auto dit    
      
  - name: python27
    commands:
      - conda install pip numpy Cython python=2.7
      - conda install scipy cvxopt
      - pip install --upgrade --ignore-installed -r requirements_testing.txt     
      - pip install .
      - pip install -r requirements_optional.txt
      - pytest --numprocesses=auto dit
      
ci:
  builds:
    - name: python37
      build_target: python37
    - name: python36
      build_target: python36
    - name: python35
      build_target: python35
    - name: python27
      build_target: python27
      
